// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AutoclickVisibleController from "./autoclick_visible_controller"
application.register("autoclick-visible", AutoclickVisibleController)

import CommentsController from "./comments_controller"
application.register("comments", CommentsController)

import LikesController from "./likes_controller"
application.register("likes", LikesController)

import ModalController from "./modal_controller"
application.register("modal", ModalController)

import TimeAgoController from "./time_ago_controller"
application.register("time-ago", TimeAgoController)
